/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new course
     * @description Creates a new course associated with the authenticated user.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Course creation request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.CourseCreateDTO"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.CourseResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to create course */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a course
     * @description Retrieves a course by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Course ID */
          courseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.CourseResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Course not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve course */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a course
     * @description Deletes a course and all its lectures, removes associated PDFs from storage, clears any pending jobs in ingestion, embedding, explanation, and summary queues, and deletes related database records.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Course ID */
          courseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Course not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to delete course */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a course
     * @description Updates an existing course by its ID.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Course ID */
          courseId: string;
        };
        cookie?: never;
      };
      /** @description Course update request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.CourseUpdateDTO"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.CourseResponseDTO"];
          };
        };
        /** @description Invalid JSON payload, validation failed, or title cannot be empty */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Course not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to update course */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    trace?: never;
  };
  "/dlq": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Process dead-letter queue message
     * @description Receives a Pub/Sub push from a dead-letter topic and persists the message to the database for manual inspection.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Dead-letter queue Pub/Sub push payload */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.PubSubPushRequest"];
        };
      };
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Invalid request body or format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List lectures
     * @description Retrieves lectures filtered by course_id with pagination
     */
    get: {
      parameters: {
        query: {
          /** @description Course ID */
          course_id: string;
          /** @description Limit number of lectures */
          limit?: number;
          /** @description Pagination offset */
          offset?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureResponseDTO"][];
          };
        };
        /** @description Missing or invalid course_id */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve lectures */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures/batch-upload-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get upload URLs for lectures
     * @description Initiates lecture uploads by creating lecture records and returning presigned URLs for direct S3 upload. Works for both single and multiple files.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Upload URL request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.LectureUploadURLRequestDTO"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureBatchUploadURLResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Upload limit exceeded */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Course not found or access denied */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to create upload URLs */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures/{lectureId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a lecture
     * @description Retrieves a lecture by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve lecture */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a lecture
     * @description Deletes a lecture and all its derived database records, removes its PDF from storage, and clears related pending jobs from ingestion, embedding, explanation, and summary queues.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to delete lecture */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a lecture
     * @description Updates lecture metadata including title, accessed_at, and course_id.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      /** @description Lecture update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.LectureUpdateDTO"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureResponseDTO"];
          };
        };
        /** @description Invalid JSON payload, title cannot be empty, or course_id cannot be empty */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found or course not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to update lecture */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    trace?: never;
  };
  "/lectures/{lectureId}/chats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List chats for a lecture
     * @description Retrieves all chats for a specific lecture with pagination support.
     */
    get: {
      parameters: {
        query?: {
          /** @description Maximum number of chats to return */
          limit?: number;
          /** @description Number of chats to skip */
          offset?: number;
        };
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.ChatResponseDTO"][];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to list chats */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new chat
     * @description Creates a new chat conversation for a lecture. The chat title is optional and defaults to "New Chat".
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      /** @description Chat creation request */
      requestBody?: {
        content: {
          "application/json": components["schemas"]["dto.ChatCreateDTO"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.ChatResponseDTO"];
          };
        };
        /** @description Invalid JSON payload */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to create chat */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures/{lectureId}/chats/{chatId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a chat
     * @description Retrieves a specific chat by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
          /** @description Chat ID */
          chatId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.ChatResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Chat not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to get chat */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a chat
     * @description Deletes a chat and all its associated messages.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
          /** @description Chat ID */
          chatId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": string;
          };
        };
        /** @description Chat not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": string;
          };
        };
        /** @description Failed to delete chat */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a chat
     * @description Updates a chat's title.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
          /** @description Chat ID */
          chatId: string;
        };
        cookie?: never;
      };
      /** @description Chat update request */
      requestBody?: {
        content: {
          "application/json": components["schemas"]["dto.ChatUpdateDTO"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.ChatResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Chat not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to update chat */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    trace?: never;
  };
  "/lectures/{lectureId}/chats/{chatId}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List messages in a chat
     * @description Retrieves all messages for a specific chat. Messages are returned in chronological order (oldest first).
     */
    get: {
      parameters: {
        query?: {
          /** @description Maximum number of messages to return */
          limit?: number;
        };
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
          /** @description Chat ID */
          chatId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.MessageResponseDTO"][];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Chat not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to list messages */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures/{lectureId}/chats/{chatId}/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stream chat response
     * @description Sends a user message and streams the AI assistant's response using Server-Sent Events (SSE). The user message is saved immediately, and the assistant response is saved after streaming completes. The model parameter specifies which LLM model to use for the response.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
          /** @description Chat ID */
          chatId: string;
        };
        cookie?: never;
      };
      /** @description Chat stream request with message parts and model */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.ChatStreamRequestDTO"];
        };
      };
      responses: {
        /** @description Server-Sent Events stream */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Invalid JSON payload, validation failed, or API key required */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Chat or lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Failed to stream chat response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures/{lectureId}/explanations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List lecture explanations (DEPRECATED)
     * @deprecated
     * @description DEPRECATED: This endpoint is no longer actively generating new explanations. Explanation generation (Step 5 in data flow) has been removed. This endpoint may still return legacy data from existing lectures but will return empty arrays for newly uploaded lectures.
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit number of results (if omitted, returns all explanations) */
          limit?: number;
          /** @description Pagination offset (default 0) */
          offset?: number;
        };
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureExplanationResponseDTO"][];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve explanations */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures/{lectureId}/note": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a lecture note
     * @description Creates a new note for a lecture.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      /** @description Note create data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.LectureNoteCreateDTO"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureNoteResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to create note */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update a lecture note
     * @description Updates the content of a note for a lecture.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      /** @description Note update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.LectureNoteUpdateDTO"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureNoteResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to update note */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    trace?: never;
  };
  "/lectures/{lectureId}/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get lecture summary (DEPRECATED)
     * @deprecated
     * @description DEPRECATED: This endpoint is no longer actively generating new summaries. Summary generation (Step 6 in data flow) has been removed. This endpoint may still return legacy data from existing lectures but will return empty content for newly uploaded lectures.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureSummaryResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve summary */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures/{lectureId}/upload-complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete lecture upload
     * @description Finalizes a lecture upload by verifying the file exists in storage and triggering processing.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      /** @description Upload complete request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.LectureUploadCompleteRequestDTO"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.LectureUploadCompleteResponseDTO"];
          };
        };
        /** @description Invalid JSON payload */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found or access denied */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to complete upload */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/lectures/{lectureId}/url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get signed URL for lecture PDF
     * @description Generates a signed URL for downloading the lecture PDF.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lecture ID */
          lectureId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.SignedURLResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Lecture not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to generate signed URL */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user profile
     * @description Retrieves the profile of the authenticated user.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.UserResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    /**
     * Create or update a user profile
     * @description Creates a new user profile or updates an existing one associated with the authenticated user ID.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description User creation request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.UserCreateDTO"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.UserResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to create user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/api-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Store user's API key
     * @description Stores the user's API key securely in Google Cloud Secret Manager and updates the user profile flag. Supports providers: openai, gemini, anthropic, xai, and deepseek.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description API key request with provider (openai, gemini, anthropic, xai, or deepseek) */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.APIKeyRequestDTO"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.APIKeyResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to store API key */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    /**
     * Delete user's API key
     * @description Deletes the user's API key from Google Cloud Secret Manager and updates the user profile flag.
     */
    delete: {
      parameters: {
        query: {
          /** @description API provider (openai, gemini, anthropic, xai, or deepseek) */
          provider: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.APIKeyResponseDTO"];
          };
        };
        /** @description Invalid provider parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to delete API key */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user's courses
     * @description Retrieves the list of courses associated with the authenticated user, sorted by most recent update.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.UserCourseResponseDTO"][];
          };
        };
        /** @description Unauthorized: user ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve user courses */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List available models for the user
     * @description Returns curated models for providers where the user has added API keys, including enabled state
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.ModelsResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to list models */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    /**
     * Update a model enablement preference
     * @description Toggles a curated model for a provider for the current user
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Model preference update */
      requestBody: {
        content: {
          "application/json": components["schemas"]["dto.ModelPreferenceRequestDTO"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.ModelToggleDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to update model preference */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/recents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get recent lectures with count
     * @description Retrieves a list of recently viewed lectures for the authenticated user with total count.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of lectures to return (default 10) */
          limit?: number;
          /** @description Offset for pagination (default 0) */
          offset?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["dto.UserRecentLecturesResponseDTO"];
          };
        };
        /** @description Unauthorized: user ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve recent lectures */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "dto.APIKeyRequestDTO": {
      api_key: string;
      /** @enum {string} */
      provider: "openai" | "gemini" | "anthropic" | "xai" | "deepseek";
    };
    "dto.APIKeyResponseDTO": {
      has_provided_key?: boolean;
      provider?: string;
    };
    "dto.ChatCreateDTO": {
      title?: string;
    };
    "dto.ChatResponseDTO": {
      created_at?: string;
      id?: string;
      lecture_id?: string;
      title?: string;
      updated_at?: string;
      user_id?: string;
    };
    "dto.ChatStreamRequestDTO": {
      model: string;
      parts: components["schemas"]["dto.MessagePartDTO"][];
    };
    "dto.ChatUpdateDTO": {
      title?: string;
    };
    "dto.CourseCreateDTO": {
      description?: string;
      is_default?: boolean;
      title: string;
    };
    "dto.CourseResponseDTO": {
      course_id?: string;
      created_at?: string;
      description?: string;
      is_default?: boolean;
      title?: string;
      updated_at?: string;
      user_id?: string;
    };
    "dto.CourseUpdateDTO": {
      description?: string;
      is_default?: boolean;
      title?: string;
    };
    "dto.LectureBatchUploadURLResponseDTO": {
      uploads?: components["schemas"]["dto.LectureUploadURLResponseDTO"][];
    };
    "dto.LectureExplanationResponseDTO": {
      content?: string;
      created_at?: string;
      id?: string;
      lecture_id?: string;
      slide_number?: number;
      updated_at?: string;
    };
    "dto.LectureNoteCreateDTO": {
      content: string;
    };
    "dto.LectureNoteResponseDTO": {
      content?: string;
      created_at?: string;
      id?: string;
      lecture_id?: string;
      updated_at?: string;
    };
    "dto.LectureNoteUpdateDTO": {
      content: string;
    };
    "dto.LectureResponseDTO": {
      accessed_at?: string;
      course_id?: string;
      created_at?: string;
      lecture_id?: string;
      status?: string;
      storage_path?: string;
      title?: string;
      updated_at?: string;
    };
    "dto.LectureSummaryResponseDTO": {
      content?: string;
      lecture_id?: string;
    };
    "dto.LectureUpdateDTO": {
      accessed_at?: string;
      course_id?: string;
      title?: string;
    };
    "dto.LectureUploadCompleteRequestDTO": Record<string, never>;
    "dto.LectureUploadCompleteResponseDTO": {
      course_id?: string;
      lecture_id?: string;
      message?: string;
      status?: string;
    };
    "dto.LectureUploadURLRequestDTO": {
      course_id: string;
      filenames: string[];
    };
    "dto.LectureUploadURLResponseDTO": {
      lecture_id?: string;
      upload_url?: string;
    };
    "dto.MessagePartDTO": {
      data?: components["schemas"]["dto.ReferencePartDTO"];
      reference?: components["schemas"]["dto.ReferenceDTO"];
      text?: string;
      type?: string;
    };
    "dto.MessageResponseDTO": {
      chat_id?: string;
      created_at?: string;
      id?: string;
      parts?: components["schemas"]["dto.MessagePartDTO"][];
      role?: string;
    };
    "dto.ModelPreferenceRequestDTO": {
      enabled?: boolean;
      model: string;
      /** @enum {string} */
      provider: "openai" | "gemini" | "anthropic" | "xai" | "deepseek";
    };
    "dto.ModelToggleDTO": {
      enabled?: boolean;
      id?: string;
      name?: string;
    };
    "dto.ModelsResponseDTO": {
      providers?: components["schemas"]["dto.ProviderModelsDTO"][];
    };
    "dto.ProviderModelsDTO": {
      models?: components["schemas"]["dto.ModelToggleDTO"][];
      provider?: string;
    };
    "dto.PubSubMessage": {
      attributes?: {
        [key: string]: string;
      };
      /** @description Base64-encoded */
      data?: string;
      messageId?: string;
    };
    "dto.PubSubPushRequest": {
      message?: components["schemas"]["dto.PubSubMessage"];
      subscription?: string;
    };
    "dto.ReferenceDTO": {
      id?: string;
      metadata?: {
        [key: string]: unknown;
      };
      type?: string;
    };
    "dto.ReferencePartDTO": {
      reference?: components["schemas"]["dto.ReferenceDTO"];
      text?: string;
      type?: string;
    };
    "dto.SignedURLResponseDTO": {
      url?: string;
    };
    "dto.UserCourseResponseDTO": {
      course_id?: string;
      description?: string;
      is_default?: boolean;
      title?: string;
      updated_at?: string;
    };
    "dto.UserCreateDTO": {
      avatar_url?: string;
      email?: string;
      name?: string;
    };
    "dto.UserRecentLectureResponseDTO": {
      course_id?: string;
      lecture_id?: string;
      title?: string;
    };
    "dto.UserRecentLecturesResponseDTO": {
      lectures?: components["schemas"]["dto.UserRecentLectureResponseDTO"][];
      total_count?: number;
    };
    "dto.UserResponseDTO": {
      api_keys_provided?: {
        [key: string]: boolean;
      };
      avatar_url?: string;
      created_at?: string;
      email?: string;
      model_preferences?: {
        [key: string]: {
          [key: string]: boolean;
        };
      };
      name?: string;
      updated_at?: string;
      user_id?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
