/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new course
     * @description Creates a new course associated with the authenticated user.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Course creation request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["app_internal_api_v1_dto.CourseCreateDTO"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["app_internal_api_v1_dto.CourseResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to create course */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a course
     * @description Retrieves a course by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Course ID */
          courseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["app_internal_api_v1_dto.CourseResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Course not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve course */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    /**
     * Update a course
     * @description Updates an existing course by its ID.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Course ID */
          courseId: string;
        };
        cookie?: never;
      };
      /** @description Course update request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["app_internal_api_v1_dto.CourseUpdateDTO"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["app_internal_api_v1_dto.CourseResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Course not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to update course */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    post?: never;
    /**
     * Delete a course
     * @description Deletes an existing course by its ID and cascades deletion of related data.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Course ID */
          courseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": string;
          };
        };
        /** @description Course not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": string;
          };
        };
        /** @description Failed to delete course */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": string;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user profile
     * @description Retrieves the profile of the authenticated user.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["app_internal_api_v1_dto.UserResponseDTO"];
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    /**
     * Create or update a user profile
     * @description Creates a new user profile or updates an existing one associated with the authenticated user ID.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description User creation request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["app_internal_api_v1_dto.UserCreateDTO"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["app_internal_api_v1_dto.UserResponseDTO"];
          };
        };
        /** @description Invalid JSON payload or validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Unauthorized: User ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to create user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user's courses
     * @description Retrieves the list of courses associated with the authenticated user, sorted by most recent update.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["app_internal_api_v1_dto.UserCourseResponseDTO"][];
          };
        };
        /** @description Unauthorized: user ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve user courses */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/recents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get recent lectures
     * @description Retrieves a list of recently viewed lectures for the authenticated user.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of lectures to return (default 10) */
          limit?: number;
          /** @description Offset for pagination (default 0) */
          offset?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["app_internal_api_v1_dto.UserRecentLectureResponseDTO"][];
          };
        };
        /** @description Unauthorized: user ID not found in context */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
        /** @description Failed to retrieve recent lectures */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "app_internal_api_v1_dto.CourseCreateDTO": {
      description?: string;
      is_default?: boolean;
      title: string;
    };
    "app_internal_api_v1_dto.CourseResponseDTO": {
      course_id?: string;
      created_at?: string;
      description?: string;
      is_default?: boolean;
      title?: string;
      updated_at?: string;
      user_id?: string;
    };
    "app_internal_api_v1_dto.CourseUpdateDTO": {
      description?: string;
      is_default?: boolean;
      title?: string;
    };
    "app_internal_api_v1_dto.UserCourseResponseDTO": {
      course_id?: string;
      description?: string;
      is_default?: boolean;
      title?: string;
      updated_at?: string;
    };
    "app_internal_api_v1_dto.UserCreateDTO": {
      avatar_url?: string;
      email?: string;
      name?: string;
    };
    "app_internal_api_v1_dto.UserRecentLectureResponseDTO": {
      lecture_id?: string;
      title?: string;
    };
    "app_internal_api_v1_dto.UserResponseDTO": {
      avatar_url?: string;
      created_at?: string;
      email?: string;
      name?: string;
      updated_at?: string;
      user_id?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
